#!/usr/bin/env python3
"""Generate static/geo-fixture.json: what engine/nav.py says, for static/geo.js to match.

    python3 scripts/gen_geo_fixture.py

The map draws marks, the start line, the course and the boat in one picture; the engine
decides which leg the boat is on and whether it has crossed the line. Both work in the
same local ENU frame, and if the browser's copy of that frame differs from the engine's
then the boat sits off the marks and the start line stops agreeing with the geometry the
finish is detected against. It would look like bad mark data and would not be.

So geo.js is a transcription of nav.py rather than a reimplementation, and this is the
oracle that holds it to that. Section 6 of DESIGN already uses the register's own MGA94
easting and northing columns as free fixtures for the same function; this is the same idea
with nav.py as the authority instead.

The fixture is committed, so the check needs no Python. Regenerate it when nav.py's
projection changes, which should be approximately never: a change there is a change to
where every mark is, and the replayed race in tests/test_race.py would move with it.

Deliberately covers three things, because the transcription can go wrong in three places:

- metres_per_degree across a wide span of latitude, which is where using one spherical
  constant instead of two radii of curvature shows up.
- enu() for every mark in marks.json, against the start line's inner end as origin, plus
  the corners of both bounding boxes so the far field is covered as well as the racing
  area.
- norm180() over a range that includes negative multiples of 360. This is the one function
  where the two languages genuinely differ: Python's % returns the sign of the divisor and
  JavaScript's returns the sign of the dividend, so a faithful-looking copy is wrong for
  every negative input. Nothing on the Swan needs it, and it is here because a piece
  transcribed wrongly and never exercised is how the two files drift apart later.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))

from engine import nav  # noqa: E402

OUT = ROOT / "static" / "geo-fixture.json"


def main() -> int:
    marks = json.loads((ROOT / "config" / "marks.json").read_text(encoding="utf-8"))
    lines = json.loads((ROOT / "config" / "lines.json").read_text(encoding="utf-8"))
    coast = json.loads((ROOT / "config" / "coast.json").read_text(encoding="utf-8"))

    # The origin is the inner end of the start line, which is where the map's own frame
    # will be centred: it is the one point on the course that never moves between races.
    inner = lines["start_finish"]["inner"]
    origin = {"lat": inner["lat"], "lon": inner["lon"]}

    points = [{"id": m["id"], "lat": m["lat"], "lon": m["lon"]} for m in marks["marks"]]
    for label, box in (("marks", marks["bbox"]), ("coast", coast["bbox"])):
        for ns in ("south", "north"):
            for ew in ("west", "east"):
                points.append({"id": "%s-bbox-%s-%s" % (label, ns, ew),
                               "lat": box[ns], "lon": box[ew]})

    fixture = {
        "schema": "geo-fixture/1",
        "note": ("Generated by scripts/gen_geo_fixture.py from engine/nav.py. "
                 "static/geo-check.html asserts static/geo.js reproduces every value "
                 "here. Do not hand-edit: regenerate."),
        "origin": origin,
        "tolerance_m": 1e-6,
        "tolerance_deg": 1e-9,
        "metres_per_degree": [],
        "enu": [],
        "norm180": [],
    }

    # A span far wider than the racing area, so a wrong formula cannot hide inside a
    # latitude range where the two radii happen to agree.
    for lat in (-60.0, -45.0, -32.5, -32.0031847, -32.0, -20.0, 0.0, 20.0, 45.0, 60.0):
        m_lat, m_lon = nav.metres_per_degree(lat)
        fixture["metres_per_degree"].append({"lat": lat, "m_lat": m_lat, "m_lon": m_lon})

    for point in points:
        e, n = nav.enu(origin, point)
        fixture["enu"].append({"id": point["id"], "lat": point["lat"],
                               "lon": point["lon"], "e": e, "n": n})

    for deg in (0.0, 1.0, 90.0, 179.9, 180.0, 180.1, 270.0, 359.9, 360.0, 540.0, 720.0,
                -1.0, -90.0, -179.9, -180.0, -180.1, -270.0, -359.9, -360.0, -540.0,
                -720.0, -1000.0, 1000.0):
        fixture["norm180"].append({"deg": deg, "want": nav.norm180(deg)})

    OUT.write_text(json.dumps(fixture, indent=1) + "\n", encoding="utf-8")
    print("%s: %d enu points, %d latitudes, %d angles, %d bytes"
          % (OUT.relative_to(ROOT), len(fixture["enu"]),
             len(fixture["metres_per_degree"]), len(fixture["norm180"]),
             OUT.stat().st_size))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
