# -*- coding: utf-8 -*-
"""Generate static/palette.js, the speed-over-ground colour scale.

    cd static && python ../scripts/gen_palette.py

The scale is matplotlib's viridis, sampled at the centre of each band, over a fixed
0 to 8 kt domain. Two things draw a speed-coloured track from the same readings and they
must not disagree:

  * the map page's snail trail, in static/map.js, which is this file's only consumer;
  * event_recorder's route map, which colours a processed recording with matplotlib
    directly.

So matplotlib is the single source of truth for the palette and this script transcribes
it, exactly as static/geo.js is a transcription of engine/nav.py rather than a second
implementation of the projection. The alternative was a hand-copied table of hex values in
the JavaScript, which is the same thing without the guarantee that it still matches.

matplotlib is not in requirements.txt and must not be: nothing is installed at runtime and
the app serves the generated file. This is a dock-side developer tool like every other
gen_*.py here, and its output is committed.

Why a fixed domain rather than one scaled to the day. A colour has to mean a speed, not a
rank: the crew reads the trail against the last hour and against last Saturday, and a
scale that stretched to fit whatever has happened so far would repaint the whole trail
every time a gust arrived. 8 kt is the top because Enchantee does not exceed it under sail
in the river; anything faster clamps to the last band rather than rescaling the rest.

Why sixteen bands. It is the point where a band edge stops being visible as a step on a
2.5 px line, and it is also what keeps the drawn trail to sixteen SVG paths regardless of
how many points are in it. See DESIGN 12.6: one path per band is the whole reason the
trail can hold a day of fixes on the boat's iPad.
"""

from __future__ import annotations

import json
from pathlib import Path

BANDS = 16
MIN_KT = 0.0
MAX_KT = 8.0

UNKNOWN = "#8a8a8a"
"""For a fix that arrived with no usable speed. Deliberately outside viridis and
deliberately drab: it has to read as "no reading" rather than as a speed, and every
viridis colour reads as a speed."""

HEADER = """// Speed-over-ground colour scale, shared by the map's snail trail and event_recorder's
// route maps. GENERATED by scripts/gen_palette.py from matplotlib's viridis; edit that
// script and re-run it, not this file.
//
// {bands} bands over a fixed {min_kt} to {max_kt} kt domain. Fixed, so a colour means a speed rather
// than a rank: a scale stretched to the day's fastest reading would repaint the whole
// trail whenever a gust arrived, and would not compare with last Saturday. Speeds above
// the top clamp to the last band.
//
// var and function to match app.js, map.js and geo.js, which are written that way
// throughout.
"""


def viridis_hex(n: int) -> list[str]:
    """The n band colours, sampled at band centres.

    Centres rather than edges: sampling at i/(n-1) would put pure viridis endpoints on the
    two outer bands and squeeze the rest, so a band's colour would not be the colour of
    the speeds in it.
    """
    from matplotlib import colormaps

    cmap = colormaps["viridis"]
    out = []
    for i in range(n):
        r, g, b, _ = cmap((i + 0.5) / n)
        out.append("#%02x%02x%02x" % (round(r * 255), round(g * 255), round(b * 255)))
    return out


def render(colours: list[str]) -> str:
    header = HEADER.format(bands=BANDS, min_kt=int(MIN_KT), max_kt=int(MAX_KT))
    swatches = ",\n".join("    " + json.dumps(c) for c in colours)
    return header + """
window.Palette = (function () {
  "use strict";

  var MIN_KT = %(min_kt)s;
  var MAX_KT = %(max_kt)s;

  var BANDS = [
%(swatches)s
  ];

  // A fix that arrived with no usable speed. Kept as a band of its own rather than
  // dropped: dropping it would draw a straight line between the fixes either side and
  // claim the boat sailed a course it did not.
  var UNKNOWN = %(unknown)s;

  // The band a speed in knots belongs to, or -1 for "no reading". Clamped at both ends,
  // so a spurious 40 kt from a bad fix colours one segment and does not rescale the map.
  function band(kt) {
    if (typeof kt !== "number" || !isFinite(kt)) return -1;
    var t = (kt - MIN_KT) / (MAX_KT - MIN_KT);
    var i = Math.floor(t * BANDS.length);
    if (i < 0) i = 0;
    if (i >= BANDS.length) i = BANDS.length - 1;
    return i;
  }

  // The colour for a band index, UNKNOWN for -1. One place that mapping happens, so a
  // caller never indexes BANDS with a -1 and gets undefined.
  function colour(i) {
    return (i < 0 || i >= BANDS.length) ? UNKNOWN : BANDS[i];
  }

  return { BANDS: BANDS, UNKNOWN: UNKNOWN, MIN_KT: MIN_KT, MAX_KT: MAX_KT,
           band: band, colour: colour };
}());
""" % {
        "min_kt": int(MIN_KT) if MIN_KT == int(MIN_KT) else MIN_KT,
        "max_kt": int(MAX_KT) if MAX_KT == int(MAX_KT) else MAX_KT,
        "swatches": swatches,
        "unknown": json.dumps(UNKNOWN),
    }


def main() -> None:
    colours = viridis_hex(BANDS)
    Path("palette.js").write_text(render(colours), encoding="utf-8")
    print("palette.js: %d bands, %g to %g kt" % (BANDS, MIN_KT, MAX_KT))
    for i, c in enumerate(colours):
        lo = MIN_KT + (MAX_KT - MIN_KT) * i / BANDS
        hi = MIN_KT + (MAX_KT - MIN_KT) * (i + 1) / BANDS
        print("  %2d  %4.1f-%4.1f kt  %s" % (i, lo, hi, c))


if __name__ == "__main__":
    main()
