{
 "title": "Rain water",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rainfall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Cumultative rainfall",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rain",
     "query": "SELECT CUMULATIVE_SUM(\"difference\") FROM (SELECT DIFFERENCE(\"mean\") FROM (SELECT MEAN(\"value\") FROM \"rain\" WHERE $timeFilter GROUP BY time($__interval))),\"sensorName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Garden water tank height",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tank",
     "query": "SELECT mean(\"value\") FROM \"tank\" WHERE (\"sensorGroup\"::tag = 'Garden water tank' OR \"sensorGroup\"::tag = 'Green water tank') AND $timeFilter GROUP BY time($__interval), \"sensorName\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup::tag", "operator": "=", "value": "Garden water tank" },
      { "condition": "OR", "key": "sensorGroup::tag", "operator": "=", "value": "Green water tank" }
     ]
    }
   ]
  },
  {
   "title": "Garden Water Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "query": "SELECT difference(mean(\"value\")) FROM \"water\" WHERE $timeFilter GROUP BY time($__interval), \"sensorName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName::tag", "operator": "=", "value": "Green tank" }
     ]
    }
   ]
  }
 ]
}