{
 "title": "Temperatures",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT mean(\"sensor 1\"), mean(\"Kitchen\") FROM \"temperature\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "<>", "value": "Hot water system" },
      { "condition": "AND", "key": "sensorGroup", "operator": "<>", "value": "beehive" },
      { "condition": "AND", "key": "sensorGroup", "operator": "<>", "value": "Fridge temperatures" },
      { "condition": "AND", "key": "sensorGroup", "operator": "<>", "value": "Solar tester" }
     ]
    }
   ]
  },
  {
   "title": "Hot water system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "=", "value": "Hot water system" }
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Outside",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName", "operator": "=", "value": "Rain gauge" }
     ]
    },
    {
     "alias": "Kitchen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName", "operator": "=", "value": "Kitchen" }
     ]
    },
    {
     "alias": "Hot water",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName", "operator": "=", "value": "Water (T3)" }
     ]
    },
    {
     "alias": "Upstairs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName", "operator": "=", "value": "Upstairs" }
     ]
    }
   ]
  },
  {
   "title": "Fridge Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "=", "value": "Fridge temperatures" },
      { "condition": "OR", "key": "sensorGroup", "operator": "=", "value": "Solar tester" }
     ]
    }
   ]
  }
 ]
}