{
 "title": "Water Usage",
 "time": { "from": "2024-03-09T23:27:48.333Z", "to": "2024-03-10T01:05:17.463Z" },
 "panels": [
  {
   "title": "Water usage",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName::tag", "operator": "=", "value": "Water Used" }
     ]
    }
   ]
  },
  {
   "title": "Cummulative water usage",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "query": "SELECT CUMULATIVE_SUM(\"difference\") FROM (SELECT DIFFERENCE(\"mean\") FROM (SELECT MEAN(\"value\") FROM \"water\" WHERE $timeFilter GROUP BY time($__interval)))GROUP BY \"sensorName\" fill(null)"
    }
   ]
  },
  {
   "title": "Garden water tank height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tank",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Water usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 21, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water",
     "query": "SELECT difference(mean(\"value\")) FROM \"water\" WHERE $timeFilter GROUP BY time(24h), \"sensorName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  }
 ]
}