{
 "title": "Power Copy",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Power usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"value\") FROM \"power\" WHERE (\"sensorName\" = 'Imported' OR \"sensorName\" = 'Consumed' OR \"sensorName\" = 'HWS' OR \"sensorName\" = 'Car') AND $timeFilter GROUP BY time($__interval), \"sensorName\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName", "operator": "=", "value": "Imported" },
      { "condition": "OR", "key": "sensorName", "operator": "=", "value": "Consumed" },
      { "condition": "OR", "key": "sensorName", "operator": "=", "value": "HWS" },
      { "condition": "OR", "key": "sensorName", "operator": "=", "value": "Car" }
     ]
    }
   ]
  },
  {
   "title": "Totals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 1, "x": 23, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "query": "SELECT CUMULATIVE_SUM(\"difference\") FROM (SELECT DIFFERENCE(\"mean\") FROM (SELECT MEAN(\"value\")/1000 FROM \"pulse\" WHERE (\"sensorName\" = 'Imported' OR \"sensorName\" = 'Consumed' OR \"sensorName\" = 'HWS' OR \"sensorName\" = 'Car' OR \"sensorName\" =~ /Solar/) AND $timeFilter GROUP BY time($__interval))) GROUP BY \"sensorName\""
    }
   ]
  },
  {
   "title": "Solar production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"value\") FROM \"power\" WHERE (\"sensorName\"::tag = 'Inverter Three - PV' OR \"sensorName\"::tag = 'Inverter Two - PV' OR \"sensorName\"::tag = 'Inverter One - PV') AND $timeFilter GROUP BY time($__interval), \"sensorName\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName::tag", "operator": "=", "value": "Inverter Three - PV" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "inverter/pvInputPower/1" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "power/0/1" }
     ]
    }
   ]
  },
  {
   "title": "Inverter currents",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName", "operator": "=", "value": "Inverter 1" },
      { "condition": "OR", "key": "sensorName", "operator": "=", "value": "Inverter 2" },
      { "condition": "OR", "key": "sensorName", "operator": "=", "value": "Inverter 3" }
     ]
    }
   ]
  },
  {
   "title": "Battery currents",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName", "operator": "=", "value": "Battery-280Ah" },
      { "condition": "OR", "key": "sensorName", "operator": "=", "value": "Battery-320Ah" },
      { "condition": "OR", "key": "sensorName", "operator": "=", "value": "Battery-510Ah" }
     ]
    }
   ]
  },
  {
   "title": "520Ah Battery mid-voltages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "=", "value": "Main battery monitor" }
     ]
    }
   ]
  },
  {
   "title": "520Ah single row serial voltages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "OR", "key": "sensorGroup::tag", "operator": "=", "value": "12v series monitor (NodeRed)" },
      {
       "condition": "OR",
       "key": "sensorGroup::tag",
       "operator": "=",
       "value": "12v series monitor (Normalised)"
      }
     ]
    }
   ]
  },
  {
   "title": "280Ah Cell voltages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "=", "value": "BMS - Bank 1" }
     ]
    }
   ]
  },
  {
   "title": "320Ah Cell voltages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "=", "value": "BMS - Bank 2" }
     ]
    }
   ]
  },
  {
   "title": "Different Rail voltages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName::tag", "operator": "=", "value": "BMS - Bank 1" },
      { "condition": "OR", "key": "sensorName::tag", "operator": "=", "value": "BMS - Bank 2" },
      { "condition": "OR", "key": "sensorName::tag", "operator": "=", "value": "Rail" },
      { "condition": "OR", "key": "sensorName::tag", "operator": "=", "value": "Inverter One" },
      { "condition": "OR", "key": "sensorName::tag", "operator": "=", "value": "Inverter Two" }
     ]
    },
    {
     "alias": "Series Monitor Battery 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup::tag", "operator": "=", "value": "12v series monitor" },
      { "condition": "AND", "key": "sensorName::tag", "operator": "=", "value": "Battery 4" }
     ]
    }
   ]
  },
  {
   "title": "Battery capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "capacity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName::tag", "operator": "=", "value": "BMS - Bank 1 - SoC" },
      { "condition": "OR", "key": "sensorName::tag", "operator": "=", "value": "BMS - Bank 2 - SoC" }
     ]
    }
   ]
  },
  {
   "title": "Battery pulse",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pulse",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "=", "value": "Main battery monitor" },
      { "condition": "OR", "key": "sensorGroup", "operator": "=", "value": "Reverse Current Tester" }
     ]
    }
   ]
  }
 ]
}