{
 "title": "Nissan Leaf",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Nissan Leaf",
   "type": "graph",
   "gridPos": { "h": 16, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "leaf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "=", "value": "Leaf" },
      { "condition": "AND", "key": "sensorName", "operator": "!=", "value": "Leaf - Odometer" }
     ]
    },
    {
     "alias": "Distance travelled",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CUMULATIVE_SUM(\"difference\") FROM (SELECT DIFFERENCE(\"mean\") FROM (SELECT MEAN(\"value\") FROM \"leaf\" WHERE (\"sensorName\" = 'Leaf - Odometer') AND $timeFilter GROUP BY time($__interval))),\"sensorName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Leaf state",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "leaf",
     "query": "SELECT mean(\"value\")  FROM \"leaf\" WHERE $timeFilter GROUP BY time($__interval), \"sensorName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Distance Travelled",
     "query": "SELECT CUMULATIVE_SUM(\"difference\") FROM (SELECT DIFFERENCE(\"mean\") FROM (SELECT MEAN(\"value\") FROM \"leaf\" WHERE (\"sensorName\" = 'Leaf - Odometer') AND $timeFilter GROUP BY time($__interval))),\"sensorName\" fill(null)"
    },
    {
     "alias": "Charge KW",
     "query": "SELECT CUMULATIVE_SUM(\"difference\") FROM (SELECT DIFFERENCE(\"mean\") FROM (SELECT MEAN(\"value\")/1000 FROM \"pulse\" WHERE (\"sensorName\" = 'Car') AND $timeFilter GROUP BY time($__interval))),\"sensorName\" fill(null)"
    }
   ]
  },
  {
   "title": "Car charging power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName", "operator": "=", "value": "Car" }
     ]
    }
   ]
  }
 ]
}