{
 "title": "Power",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Power usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"value\") FROM \"power\" WHERE (\"sensorName\" = 'Imported' OR \"sensorName\" = 'Consumed' OR \"sensorName\" = 'HWS' OR \"sensorName\" = 'Car') AND $timeFilter GROUP BY time($__interval), \"sensorName\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName", "operator": "=", "value": "Imported" },
      { "condition": "OR", "key": "sensorName", "operator": "=", "value": "Consumed" },
      { "condition": "OR", "key": "sensorName", "operator": "=", "value": "HWS" },
      { "condition": "OR", "key": "sensorName", "operator": "=", "value": "Car" }
     ]
    }
   ]
  },
  {
   "title": "Totals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 1, "x": 23, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "query": "SELECT CUMULATIVE_SUM(\"difference\") FROM (SELECT DIFFERENCE(\"mean\") FROM (SELECT MEAN(\"value\")/1000 FROM \"pulse\" WHERE (\"sensorName\" = 'Imported' OR \"sensorName\" = 'Consumed' OR \"sensorName\" = 'HWS' OR \"sensorName\" = 'Car' OR \"sensorName\" =~ /Solar/) AND $timeFilter GROUP BY time($__interval))) GROUP BY \"sensorName\""
    }
   ]
  },
  {
   "title": "Solar production",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "power",
     "query": "SELECT mean(\"value\") FROM \"power\" WHERE (\"sensor\" = 'select tag value') AND $timeFilter GROUP BY time($__interval), \"sensorName\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "inverter/pvInputPower/0" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "inverter/pvInputPower/1" }
     ]
    }
   ]
  },
  {
   "title": "Batteries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorName", "operator": "=", "value": "Bank 1" },
      { "condition": "OR", "key": "sensorName", "operator": "=", "value": "Bank 2" },
      { "condition": "OR", "key": "sensorName", "operator": "=", "value": "Bank 3 (old batteries)" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "=", "value": "Battery monitor" }
     ]
    }
   ]
  },
  {
   "title": "Battery capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "capacity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery pulse",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pulse",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "=", "value": "Battery monitor" }
     ]
    }
   ]
  }
 ]
}