{
 "title": "Temperatures",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT mean(\"sensor 1\"), mean(\"Kitchen\") FROM \"temperature\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "<>", "value": "Hot water system" },
      { "condition": "AND", "key": "sensorGroup", "operator": "<>", "value": "beehive" },
      { "condition": "AND", "key": "sensorGroup", "operator": "<>", "value": "Fridge temperatures" }
     ]
    }
   ]
  },
  {
   "title": "Fridge Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "=", "value": "Fridge temperatures" }
     ]
    }
   ]
  },
  {
   "title": "Hot water system",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensorName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensorName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensorGroup", "operator": "=", "value": "Hot water system" }
     ]
    }
   ]
  }
 ]
}