version: '2'
services:
  influxdb:
    image: arm32v7/influxdb:latest
    container_name: influx
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - /share/influxdb/influxdb_backup:/backups
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_HTTP_FLUX_ENABLED=true
    restart: always
  # chronograf:
  #   image: chronograf:latest
  #   ports:
  #     - '127.0.0.1:8888:8888'
  #   volumes:
  #     - chronograf-storage:/var/lib/chronograf
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - INFLUXDB_URL=http://influxdb:8086
  #     - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
  #     - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    container_name: grafana1
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_PANELS_ENABLE_ALPHA=true
      - GF_SERVER_ROOT_URL=${GRAFANA_URL}
      - GF_SERVER_DOMAIN=${DOMAIN_NAME}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    restart: always
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - 1883:1883
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - ./mosquitto-config:/mosquitto/config
    restart: always

  emon_mqtt_to_log:
    image: sfewings32/emon_mqtt_to_log:latest
    container_name: emon_log
    volumes:
      - /share/Input:/share/Input
    depends_on:
      - mosquitto
    environment:
      - MQTT_IP=mqtt
      - TZ=${TIMEZONE}
    restart: always

  emon_serial_to_mqtt:
    image: sfewings32/emon_serial_to_mqtt:latest
    container_name: emon_serial
    devices:
      - /dev/ttyUSB0
    environment:
      - SETTINGS_PATH=/data/emon_config.yml
      - SERIAL_PORT=/dev/ttyUSB0
      - MQTT_IP=mqtt
      - TZ=${TIMEZONE}
    volumes:
      - /share/emon_Suite/python:/data
      - /share/Output:/share/Output
    depends_on:
      - mosquitto
    restart: always

  # emon_serial_to_mqtt_lora:
  #   image: sfewings32/emon_serial_to_mqtt:latest
  #   container_name: emon_serial_lora
  #   devices:
  #     - /dev/ttyUSB1
  #   environment:
  #     - SETTINGS_PATH=/data/emon_config.yml
  #     - SERIAL_PORT=/dev/ttyUSB1
  #     - MQTT_IP=mqtt
  #     - TZ=${TIMEZONE}
  #   volumes:
  #     - /share/emon_Suite/python:/data
  #   depends_on:
  #     - mosquitto
  #   restart: always
      
  emon_mqtt_to_influx:
    image: sfewings32/emon_mqtt_to_influx:latest
    container_name: emon_influx
    volumes:
      - /share/emon_Suite/python:/share/config
    environment:
      - MQTT_IP=mqtt
      - INFLUX_IP=influxdb
    depends_on:
      - influxdb
      - mosquitto
    restart: always

  node-red:
    image: nodered/node-red:latest
    container_name: node_red
    environment:
      - TZ=${TIMEZONE}
    entrypoint: /data/entrypoint.sh
    ports:
      - "1880:1880"
    volumes:
      - /share/emon-node-red:/data
      - /share:/share
      - /media:/containermedia
    depends_on:
      - mosquitto
    restart: always

  emon_logtojson:
    image: sfewings32/emon_logtojson:latest
    container_name: emon_logtojson
    volumes:
      - /share:/share
    environment:
      - TZ=${TIMEZONE}
      - MQTT_IP=mqtt
      - REPROCESS_LOGS_FROM_YEAR=this
    depends_on:
      - mosquitto
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    ports:
      - 9000:9000
      - 9443:9443

  # onedrive:
  #   image: driveone/onedrive:edge
  #   restart: unless-stopped
  #   environment:
  #     - ONEDRIVE_UID=${PUID}
  #     - ONEDRIVE_GID=${PGID}
  #     - ONEDRIVE_SINGLE_DIRECTORY= RaspPi/shannstainable
  #     - ONEDRIVE_UPLOADONLY=1
  #   volumes: 
  #     - onedrive_conf:/onedrive/conf
  #     - ${ONEDRIVE_DATA_DIR}:/onedrive/data      

#   nginx-proxy:
#     image: nginx
#     container_name: nginx-proxy
#     restart: always
#     ports:
#       - "443:443"
#       - "80:80"
#     volumes:
# #      - ./www:/var/www:ro
#       - /etc/nginx:/share/emon_Suite/LinuxInstall/etc/nginx/sites-available:ro
#       - /etc/nginx/ssl:/etc/letsencrypt/live/shannstainable.fewings.org
#      - ./ssl:/etc/letsencrypt/live/shannstainable.fewings.org
#      - ./snippets:/etc/nginx/snippets:ro
#      - ./protect:/etc/nginx/protect:ro

  # Let's Encrypt / Certbot
  # Check README.md to know how to issue new certs.
#   certbot:
#     image: certbot/certbot
#     container_name: certbot
#     depends_on:
#       - nginx-proxy
#     volumes:
#       - ./ssl:/etc/letsencrypt
#       - ./ssl-log:/var/log/letsencrypt
# #      - ./www/.well-known:/var/www/.well-known
#     profiles:
#       - certbot
#     command: [
#             "renew",
#           ]


volumes:
  influxdb-storage:
 # chronograf-storage:
  grafana-storage:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-conf:
  portainer-data:
 # onedrive_conf:
