version: '2'
services:
  influxdb:
    image: influxdb:latest
    container_name: influx
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - /share/influxdb/influxdb_backup:/backups
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_HTTP_FLUX_ENABLED=true
    restart: always
  # chronograf:
  #   image: chronograf:latest
  #   ports:
  #     - '127.0.0.1:8888:8888'
  #   volumes:
  #     - chronograf-storage:/var/lib/chronograf
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - INFLUXDB_URL=http://influxdb:8086
  #     - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
  #     - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  portainer:
    image: portainer/portainer-ce:linux-arm
    container_name: portainer
    restart: always
    ports: 
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  grafana:
    image: grafana/grafana:latest
    container_name: grafana1
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_PANELS_ENABLE_ALPHA=true
      - GF_SERVER_ROOT_URL=${GRAFANA_URL}
    restart: always
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - 1883:1883
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - ./mosquitto-config:/mosquitto/config
    restart: always

  emon_mqtt_to_log:
    image: sfewings32/emon_mqtt_to_log:latest
    container_name: emon_log
    volumes:
      - /share/Input:/share/Input
    depends_on:
      - mosquitto
    environment:
      - MQTT_IP=${MQTT_IP}
      - TZ=Australia/Perth
    restart: always

  # emon_serial_to_mqtt:
  #   image: sfewings32/emon_serial_to_mqtt:latest
  #   container_name: emon_serial
  #   devices:
  #     - /dev/ttyUSB0
  #   environment:
  #     - SETTINGS_PATH=/data/emon_config.yml
  #     - SERIAL_PORT=/dev/ttyUSB0
  #     - MQTT_IP=mqtt
  #     - TZ=Australia/Perth
  #   volumes:
  #     - /share/emon_Suite/python:/data
  #   depends_on:
  #     - mosquitto
  #   restart: always
      
  emon_mqtt_to_influx:
    image: sfewings32/emon_mqtt_to_influx:latest
    container_name: emon_influx
    volumes:
      - /share/emon_Suite/python:/share/config
      - /media/pi/510F-2D7D/Input_all:/share/Input
    environment:
      - MQTT_IP=${MQTT_IP}
      - INFLUX_IP=influxdb
    depends_on:
      - influxdb
      - mosquitto
    restart: always

  node-red:
    image: nodered/node-red:latest
    container_name: node_red
    environment:
      - TZ=Australia/Perth
    entrypoint: /data/entrypoint.sh
    ports:
      - "1880:1880"
    volumes:
      - /share/emon-node-red:/data
      - /share:/share
      - /media:/containermedia
    depends_on:
      - mosquitto
    restart: always

  emon_logtojson:
    image: sfewings32/emon_logtojson:latest
    container_name: emon_logtojson
    volumes:
      - /share:/share
    environment:
      - TZ=Australia/Perth
      - MQTT_IP=${MQTT_IP}
      - REPROCESS_LOGS_FROM_YEAR=this
    depends_on:
      - mosquitto
    restart: always


volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-conf:
  portainer_data:
