temp:
  0:
    name: House temperatures
    t0: Outside
disp:
  0:
    name: Kitchen
wtr:
  0:
    name: Rain tank
    f0: Water Used
    f0_litresPerPulse: 0.2
    h0: Rain water tank
pulse:
  0:
    name: Power board
    p0: Consumed
    p1: Produced
    p0_wPerPulse: 1
    p1_wPerPulse: 0.25
bat:
  0:
    name: Main battery monitor
    s0: Bank 1
    s1: Unused
    s2: Unused
    v0: Rail
    v0_reference: true
    v1: Mid-voltage
    v2: Unused
    v3: Unused
    v4: Unused
    v5: Unused
    v6: Unused
    v7: Unused
air:
  0:
    name: Outside
  1:
    name: Inside
inv: #inverters
  0:
    name: Giant
