version: '2'
services:
  emon_logtojson:
    image: emon_logtojson:v1
    volumes:
      - /share:/share
    environment:
      - TZ=Australia/Perth
      - MQTT_IP=mqtt
      - REPROCESS_LOGS_FROM_YEAR=2019

networks: 
  default: 
    external: 
      name: docker-compose-influxdb-grafana_default   